### ISSUE TITLE
Resource Schema is not valid

### ISSUE THREAD

**Issue by kremer-io** [schul-cloud/resources-api-v1#30]
The  [resource schema](https://github.com/schul-cloud/resources-api-v1/blob/master/schemas/resource/resource.json) is not valid. E.g. `properties` is not a top level element in the current schema.

**Comment by niccokunzmann** [comment]
- [ ] Test with: http://www.jsonschemavalidator.net/
- [ ] Recomment this tool in the specification

**Comment by niccokunzmann** [comment]
@kremer-io  		980fd83 should resolve this. Would you close the issue?

**Comment by kremer-io** [comment]
Yes, thank you @niccokunzmann
