### ISSUE TITLE
Lehrpläne einpflegen

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/resources-api-v1#4]
@ArneOb, Ich habe unter [curriculum][curriculum] ein Schema für die Lehrpläne erstellt. 

- [ ] Du kannst es anpassen und die gefundenen Lehrpläne einfügen.
- [ ] Eine Frage ist mir da zu klären: Wofür ist das Attribut "subject" gedacht? Für die Pläne? Ich habe [hier][curriculum] jetzt gesagt, dass es ein Feld `curriculum` geben sollte, wo diese Strings drin stehen.

[curriculum]: https://github.com/schul-cloud/ressources-api-v1/tree/master/schemas/curriculum

**Comment by ArneOb** [comment]
@niccokunzmann 
Hmmh, das hatte ich anders erwartet. Hier sollen also alle Rahmenpläne hinein. Das ist - je nach Bundesland - schon eine Menge Arbeit und wird zu einem laangem ENUM. Ich denke da noch einen Moment drüber nach.

**Comment by niccokunzmann** [comment]
@ArneOb Wir können alternativ auch spezifisieren, welche Lehrpläne es gibt und wie eine ID erstellt wird.
Dann können wir das Problem verschieben.

**Comment by ArneOb** [comment]
@niccokunzmann Ich sehe den Unterschied noch nicht; das Problem ist, dass die Verzeichnisse (Sites) für die Rahmenpläne sehr heterogen aufgebaut sind. Also ist die Arbeit, alle RPs zu benennen, fast die Gleiche, wie gleich den Link herauszusuchen. Leider ist die DB der KMK veraltet (2013, einige Links sind eben keine Permalinks). Trotzdem: dort gibt es eine DB-Id (index), die wir aber auch nicht nehmen müssen .... In jedem Fall probiere ich, darüber schneller als manuell die Liste zu erstellen; wenigstens für die Bundesländer, bei denen sich seit 2013 nix geändert hat.

**Comment by kremer-io** [comment]
@ArneOb Du meinst sicherlich diese [Liste](https://login.kmk.org/nidp/idff/sso?sid=0&option=credential&target=https://portal.kmk.org/ssf/a/c/p_name/ss_forum/p_action/1/binderId/247/action/view_permalink/entityType/workspace/vibeonprem_url/1&Ecom_User_ID=gastlp&Ecom_Password=gastlp)?

**Comment by niccokunzmann** [comment]
Die Diskussion um das curriculum ist, denke ich, momentan eingeschlafen.
Mein Vorschlag ist, dass wir sie wieder erwecken, wenn es einen Use-Case dafür gibt, z.B. wenn die ersten Materialien mit solchen Klassifizierungen auftauchen.
Ich denke, dass aufgrund der Bemühen, die wir reingesteckt haben, wir schnell wieder ein Anschluss finden.
Deswegen werde ich diese Issue jetzt schließen. Ihr könnt sie gerne referenzieren oder wieder öffnen, wenn sie gebraucht wird.

Hier ist der Stand von dem erwähnten Branch: https://github.com/schul-cloud/resources-api-v1/tree/issue-license-specification als Tag, damit der Branch gelöscht werden kann.
