### ISSUE TITLE
Lizenzformat spezifisieren

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/resources-api-v1#5]
Wie definieren wir Lizenzen?

## Context:

```
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
<img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
</a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Sound" property="dct:title" rel="dct:type">
TITLE</span> von 
<a xmlns:cc="http://creativecommons.org/ns#" href="http://url.url" property="cc:attributionName" rel="cc:attributionURL">
PERSON</a> ist lizenziert unter einer
 <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Namensnennung 4.0 International Lizenz</a>.<br />
Beruht auf dem Werk unter 
<a xmlns:dct="http://purl.org/dc/terms/" href="http://url.source" rel="dct:source">http://url.source</a>
.<br />Über diese Lizenz hinausgehende Erlaubnisse können Sie unter
 <a xmlns:cc="http://creativecommons.org/ns#" href="http://url.rights" rel="cc:morePermissions">
http://url.rights
</a> erhalten.
```

- https://creativecommons.org/ns#
- http://purl.org/dc/terms/

Fragen:

- Sollten wir die Attribute, die die Lizenzen haben, nochmal nach JSON überführen für bekannte Lizenzen?
- Sollten wir nur ein Feld für strukturierte XHTML-Daten machen?

@ArneOb @kremer-io Was denkt ihr?

**Comment by Charle42** [comment]
Hi,
vielleicht nutzt das wem bei der Spezifikation :

Von Wikimedia bekommt man folgende Lizenzinformationen zu einen Bild / Video : 
``` json
                            "LicenseShortName": {
                                "value": "Public domain",
                                "source": "commons-desc-page",
                                "hidden": ""
                            },
                            "UsageTerms": {
                                "value": "Public domain",
                                "source": "commons-desc-page",
                                "hidden": ""
                            },
                            "AttributionRequired": {
                                "value": "false",
                                "source": "commons-desc-page",
                                "hidden": ""
                            },
                            "Copyrighted": {
                                "value": "False",
                                "source": "commons-desc-page",
                                "hidden": ""
                            },
                            "Restrictions": {
                                "value": "",
                                "source": "commons-desc-page",
                                "hidden": ""
                            },
                            "License": {
                                "value": "pd",
                                "source": "commons-templates",
                                "hidden": ""
                            }
```
Momentan werden diese Informationen im *wikimedia-content-adapter* in Form eines Objekts( `{"value":"License.value","copyrighted":"copyrighted.value"}`) zurückgegeben.

**Comment by niccokunzmann** [comment]
@Charle42 Cool, hast du noch mehr Beispiele? Das ist oben für Public Domain.
Es gibt auch noch
- CC BY
- CC BY SA (share alike)
- CC BY NC (non-comercial)
- CC BY SA NC
- CC BY ND (no derivatives)
Wie machen die das da, was steht drin? Kann man irgendwo die Spezifikation der Attribute in der Schnittstelle durchlesen? Dann können haben wir schon eine Grundlage recht ausführlich beschrieben, an der wir uns orientieren können.

**Comment by Charle42** [comment]
@niccokunzmann  
Ja war ja auch nur ein exemplarisches Beispiel, wobei `Public Domain` am meisten vorkommt. 
Ich gehe mal davon aus das [die Lizenzen](commons.wikimedia.org/wiki/Commons:Copyright_tags) alle möglich sind zu mindestens beim [Hochladen](https://commons.wikimedia.org/wiki/Commons:Licensing/de) sind nur freie Inhalte erlaubt : 

> **Auf Wikimedia Commons sind nur freie Inhalte erlaubt**, also Bilder und andere Mediendateien, die keinen Urheberrechtsbeschränkungen unterworfen sind, die einer Nutzung von jedem, jederzeit und für jeden Zweck entgegenstehen.

**Comment by niccokunzmann** [comment]
@Charle42 welches Liyenyformat verwendest du für den [wikimedia-crawler](https://github.com/schul-cloud/wikimedia-content-adapter/blob/3fe11e1fb7c674c7711cf72d96725647d944ae30/wikimedia/FileInfoContainer.js#L54)? Magst du das als Pull-Request reintun?

**Comment by niccokunzmann** [comment]
@Charle42 wäre es ok für dich, aus `"False"` und `"True"` ein `true` und `false` zu machen?

**Comment by Charle42** [comment]
Ja ich denk das dürfte kein Problem sein aus den String ein boolean wert zu machen.

**Comment by niccokunzmann** [comment]
https://spdx.org/licenses/
