### ISSUE TITLE
Specify duration attribute

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/resources-api-v1#72]
The duration attribute is used by the [wikimedia crawler](https://github.com/schul-cloud/wikimedia-content-adapter/blob/3fe11e1fb7c674c7711cf72d96725647d944ae30/wikimedia/FileInfoContainer.js#L42) #68 We should specify how to use it.

**Comment by niccokunzmann** [comment]
@Charle42 Wie würde ein ideales Format für duration aussehen, das du gerne implementieren würdest?
Bist du zufrieden mit dem, was gerade da ist und möchtest du das in die Spezifikation tun oder hast du weitere Ideen?

**Comment by niccokunzmann** [comment]
Momentan würde es so aussehen:

    [<stunden>h][<minuten>m][<sekunden>s] oder P

**Comment by Charle42** [comment]
So wie es grade definiert ist [(Definition)](http://129.115.100.158/txlor/docs/IEEE_LOM_1484_12_1_v1_Final_Draft.pdf) ist das gut.

**Comment by niccokunzmann** [comment]
Von der Definition bin ich auf

![grafik](https://user-images.githubusercontent.com/564768/29625785-fcdd989e-882c-11e7-9c65-856e08350dc4.png)
und das gekommen:
https://www.w3.org/TR/xmlschema-2/#duration

und

> does not follow the alternative format of § 5.5.3.2.1 of [ISO 8601].

Von https://python-jsonschema.readthedocs.io/en/latest/validate/#validating-formats
kommt das:

>  RFC 3339 as mandated by the JSON Schema specification.

Das heißt, das JSONschema schon eine Zeitangabe unterstützt: http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.1

Ich würde vorschlagen, dass wir die Zeitangabe aus den JSONschema verwenden, weil wir JSONschema verwenden.

http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.1

**Comment by niccokunzmann** [comment]
Der reguläre Ausdruck für das Format aus IEEE LOM wäre 

    "P([0-9]+Y)?([0-9]+M)?([0-9]+D)?(T([0-9]+H)?([0-9]+M)?([0-9]+(\\.[0-9]+)?S)?)?"

(zu testen)
